#!/bin/bash
#version 1.0


# Variables
b='\033[1m'
u='\033[4m'
bl='\E[30m'
r='\E[31m'
g='\E[32m'
bu='\E[34m'
m='\E[35m'
c='\E[36m'
w='\E[37m'
endc='\E[0m'
enda='\033[0m'
blue='\e[1;34m'
cyan='\e[1;36m'
red='\e[1;31m'

figlet Alwys ID  | lolcat

echo -b "_____________________________________________________________"
echo -b "Tools : Alwys ID $red " |lolcat
echo -b "AUTHOR : Mr.OneJack aka Alwys ID $yellow " |lolcat
echo -b "ASSOCIATE :  Dear Mantan Maafkan aku Yang Dulu $green " |lolcat
echo -b "ASSOCIATE : Dear Mantan Maafkan aku Yang Dulu $blue " |lolcat
echo -b "ASSOCIATE : TERMUX TOOLS $white " |lolcat
echo -b "NOTE : Gunakan Tools Saya Dengan Bijak Ya  " | lolcat
echo -b "_____________________________________________________________"

###################################################
# CTRL + C
###################################################
trap ctrl_c INT
ctrl_c() {
clear
echo -b $blue"[#]> (Ctrl + C ) Detected, Trying To Exit ... " |lolcat
echo -b $green"[#]> Thanks For Using My Tools" |lolcat
sleep 1
echo ""
echo -b $yellow"[#]> Alwys ID Tools Installer" |lolcat

echo -b $red"[#]> Sampai Jumpa Lagi Kentod." |lolcat
sleep 1
exit
}

lagi=1
while [ $lagi -lt 6 ];
do
echo ""
echo -e $b "1. Install Nmap${enda}";
echo -e "============================" | lolcat
echo -e $b "2. Install Admin-finder${endcla}";
echo -e "============================" | lolcat
echo -e $b "3. Install RED_HAWK${enda}";
echo -e "============================" | lolcat
echo -e $b "4. Install Lazymux${enda}";
echo -e "============================" | lolcat
echo -e $b "5. Install Tools-X${enda}";
echo -e "============================" | lolcat
echo -e $b "6. Install Mrcakil${enda}";
echo -e "============================" | lolcat
echo -e $b "7. Install D-TECT${enda}";
echo -e "============================" | lolcat
echo -e $b "8. Install Mr.Rv1.1${enda}";
echo -e "============================" | lolcat
echo -e $b "9. Install BAJINGANv6${enda}";
echo -e "============================" | lolcat
echo -e $b "10. Install MultiBruteForce(MBF)${enda}";
echo -e "============================" | lolcat
echo -e $b "11. Install XERXES${enda}";
echo -e "============================" | lolcat
echo -e $b "12. Install LITESPAM${enda}";
echo -e "============================" | lolcat
echo -e $b "13. Install Android-Malware${enda}";
echo -e "============================" | lolcat
echo -e $b "14. Install SigPloit${enda}";
echo -e "============================" | lolcat
echo -e $b "15. Install Sn1per${enda}";
echo -e "============================" | lolcat
echo -e $b "16. Install ICG-AutoExploiterBoT${enda}";
echo -e "============================" | lolcat
echo -e $b "17. Install QRLJacking${enda}";
echo -e "============================" | lolcat
echo -e $b "18. Install txtool${enda}";
echo -e "============================" | lolcat
echo -e $b "19. Install Bulltools${enda}";
echo -e "============================" | lolcat
echo -e $b "20. Install Termux-Banner${enda}";
echo -e "============================" | lolcat
echo -e $b "21. Install udfhack${enda}";
echo -e "============================" | lolcat
echo -e $b "22. Install Mirai-Source-Code${enda}";
echo -e "============================" | lolcat
echo -e $b "23. Install Hale${enda}";
echo -e "============================" | lolcat
echo -e $b "24. Install Mirai-IoT-BotNet${enda}";
echo -e "============================" | lolcat
echo -e $b "25. Install Ufonet${enda}";
echo -e "============================" | lolcat
echo -e $b "26. Install bom${enda}";
echo -e "============================" | lolcat
echo -e $b "27. Install tool${enda}";
echo -e "============================" | lolcat
echo -e $b "28. Install BotNet${enda}";
echo -e "============================" | lolcat
echo -e $b "29. Install Malwares${enda}";
echo -e "============================" | lolcat
echo -e $b "30. Install zeus-bot${enda}";
echo -e "============================" | lolcat
echo -e $b "31. Install AutoSploit${enda}";
echo -e "============================" | lolcat
echo -e $b "32. Install IFC${enda}";
echo -e "============================" | lolcat
echo -e $b "33. Install SQLMAP${enda}";
echo -e "============================" | lolcat
echo -e $b "34. Install Spyder${enda}";
echo -e "============================" | lolcat
echo -e $b "35. Install Social-Engineer-ToolKit${enda}";
echo -e "============================" | lolcat
echo -e $b "36. Install Kawai-Botnet${enda}";
echo -e "============================" | lolcat
echo -e $b "37. Install DarkSploit${enda}";
echo -e "============================" | lolcat
echo -e $b "38. Install SH33LL${enda}";
echo -e "============================" | lolcat
echo -e $b "39. Install Evil-Create-Framework${enda}";
echo -e "============================" | lolcat
echo -e $b "40. Install Gabutz${enda}";
echo -e "============================" | lolcat
echo -e $b "41. Install RootNet${enda}";
echo -e "============================"| lolcat
echo -e $b "42. Install BadMod${enda}";
echo -e "============================" | lolcat
echo -e $b "43. Install BoomHash${enda}";
echo -e "============================" | lolcat
echo -e $b "44. Install Plutus${enda}";
echo -e "============================" | lolcat
echo -e $b "45. Install ContexPloit${enda}";
echo -e "============================" | lolcat
echo -e $b "46. Install Th3inspector${enda}";
echo -e "============================" | lolcat
echo -e $b "47. Install CreaterVirus${enda}";
echo -e "============================" | lolcat
echo -e $b "48. Install V3nom-Scanner${enda}";
echo -e "============================" | lolcat
echo -e $b "49. Install Bom Sms 3${enda}";
echo -e "============================" | lolcat
echo -e $b "50. Install WebKiller${enda}";
echo -e "============================" | lolcat
echo -e $b "51. Install Bitcoin-Hacking-Tools${enda}";
echo -e "============================" | lolcat
echo -e $b "52. Install Firefox-Plugin-Popup-Logout${enda}";
echo -e "============================" | lolcat
echo -e $b "53. Install Bitcoin-All-Key-Generator${enda}";
echo -e "============================" | lolcat
echo -e $b "54. Install My-First-Bitcoin-Miner${enda}";
echo -e "============================" | lolcat
echo -e $b "55. Install Parity-Config-Generator${enda}";
echo -e "============================" | lolcat
echo -e $b "56. Install Distributed-Bitcoin-Generator${enda}";
echo -e "============================" | lolcat
echo -e $b "57. Install Mesos-Bitcoin-Miner${enda}";
echo -e "============================" | lolcat
echo -e $b "58. Install Git_Psibot_Hacking${enda}";
echo -e "============================" | lolcat
echo -e $b "59. Install KatanaFramework${enda}";
echo -e "============================" | lolcat
echo -e $b "60. Install STP${enda}";
echo -e "============================" | lolcat
echo -e $b "61. Install Termux-Ubuntu${enda}";
echo -e "============================" | lolcat
echo -e $b "62. Install Nethuner-In-Termux${enda}";
echo -e "============================" | lolcat
echo -e $b "63. Install viSQL${enda}";
echo -e "============================" | lolcat
echo -e $b "64. Install Termux-Archlinux${enda}";
echo -e "============================" | lolcat
echo -e $b "65. Install Santet-Online${enda}";
echo -e "============================" | lolcat
echo -e $b "66. Install GadoGado${enda}";
echo -e "============================" | lolcat
echo -e $b "67. Install CnkSpam${enda}";
echo -e "============================" | lolcat
echo -e $b "68. Install AutoReportFB${enda}";
echo -e "============================" | lolcat
echo -e $b "69. Install Google-Dork${enda}";
echo -e "============================" | lolcat
echo -e $b "70. Install FHX-Hash-Killer${enda}";
echo -e "============================" | lolcat
echo -e $b "71. Install Hash-Buster${enda}";
echo -e "============================" | lolcat
echo -e $b "72. Install Metasploit${enda}";
echo -e "============================" | lolcat
echo -e $b "73. Install Striker${enda}";
echo -e "============================" | lolcat
echo -e $b "74. Install AutoScriptKiddieTool${enda}";
echo -e "============================" | lolcat
echo -e $b "75. Install Weeman${enda}";
echo -e "============================" | lolcat
echo -e $b "76. Install SCANNER-INURLBR${enda}";
echo -e "============================" | lolcat
echo -e $b "77. Install Script-Deface-Creator${enda}";
echo -e "============================" | lolcat
echo -e $b "78. Install ktpKkGenerate${enda}";
echo -e "============================" | lolcat
echo -e $b "79. Install ReconDog${enda}";
echo -e "============================" | lolcat
echo -e $b "80. Install HakkuFramework${enda}";
echo -e "============================" | lolcat
echo -e $b "81. Install HunnerFramework${enda}";
echo -e "============================" | lolcat
echo -e $b "82. Install Hammer${enda}";
echo -e "============================" | lolcat
echo -e $b "83. Install Torshammer${enda}";
echo -e "============================" | lolcat
echo -e $b "84. Install Katoolin${enda}";
echo -e "============================" | lolcat
echo -e $b "85. Install MPSYT${enda}";
echo -e "============================" | lolcat
echo -e $b "86. Install A-Rat${enda}";
echo -e "============================" | lolcat
echo -e $b "87. Install Cupp${enda}";
echo -e "============================" | lolcat
echo -e $b "88. Install Webpwn3r${enda}";
echo -e "============================" | lolcat
echo -e $b "89. Install IPGeolocation${enda}";
echo -e "============================" | lolcat
echo -e $b "90. Install XL${enda}";
echo -e "============================" | lolcat
echo -e $b "91. Install BotFbBangDjon${enda}";
echo -e "============================" | lolcat
echo -e $b "92. Install 4wsectools${enda}";
echo -e "============================" | lolcat
echo -e $b "93. Install Admin_Penal${enda}";
echo -e "============================" | lolcat
echo -e $b "94. Install RouterSploit${enda}";
echo -e "============================" | lolcat
echo -e $b "95. Install RusSpam${enda}";
echo -e "============================" | lolcat
echo -e $b "96. Install Jexboss${enda}";
echo -e "============================" | lolcat
echo -e $b "97. Install WifiPhisher${enda}";
echo -e "============================" | lolcat
echo -e $b "98. Install WebSploit${enda}";
echo -e "============================" | lolcat
echo -e $b "99. Install Wifi-Hacker${enda}";
echo -e "============================" | lolcat
echo -e $b "100. Install Mr.Rv1${enda}";
echo -e "============================" | lolcat
echo -e $b "101. Install Mr.Rv.2${enda}";
echo -e "============================" | lolcat
echo -e $b "102. Install semut${enda}";
echo -e "============================" | lolcat
echo -e $b "103. Install mrplug1n-nolife${enda}"; | lolcat
echo -e "============================" | lolcat
echo -e $b "00. Exit${enda}";
echo -e "╭─Alwys ID[PILIH NOMORNYA]" | lolcat
read -p "╰─#" pil;

# Nmap

case $pil in
1) pkg install nmap
echo -e "${y} {1} Masukkan Web${endc}:"
read web
nmap $web
echo

;;

#Install  admin-finder

2) git clone https://github.com/the-c0d3r/admin-finder.git
echo -e "${y} cara menggunakan admin finder"
echo -e "${y} cd admin-finder"
echo -e "${y} python admin-finder.py"

echo

;;

#Install RED_HAWK

3) git clone https://github.com/Tuhinshubhra/RED_HAWK
echo -e "${y} Installer RED_HAWK..."
echo -e "${y} cd RED_HAWK"
echo -e "${y} php r_hawk.php"


;;

#Install Lazymux

4) git clone https://github.com/Gameye98/Lazymux
echo -e "${y} Installer Lazymux..."
echo -e "${y} cd Lazymux"
echo -e "${y} python2 lazymux.py"


;;

#Install Tools-X

5) git clone https://github.com/Rajkumrdusad/Tool-X
echo -e "${y} Installer Tool-X..."
echo -e "${y} cd Tool-X"
echo -e "${y} ./install.aex"


;;

#Install Mrcakil

6) git clone https://github.com/mrcakil/Mrcakil.git
echo -e "${y} installer Mrcakil..."
echo -e "${y} cd Mrcakil"
echo -e "${y} chmod 777 tools"
echo -e "${y} ./tools"


;;

#Install D-TECT

7) git clone https://github.com/shawarkhanethicalhacker/D-TECT
echo -e "${y} cara menggunakan D-TECT..."
echo -e "${y} cd D-TECT"
echo -e "${y} chmod +x d-tect.py"
echo -e "${y} python2 d-tect.py"


;;

#Install Mr.Rv1.1

8) git clone https://github.com/Mr-R225/Mr.Rv1.1
echo -e "${y} installer Mr.Rv1.1..."
echo -e "${y} cd Mr.Rv1.1"
echo -e "${y} sh Mr.Rv1.1.sh"


;;

#Install BAJINGANv6

9) git clone https://github.com/DarknessCyberTeam/BAJINGANv6
echo -e "${y} cara menggunakan BAJINGANv6..."
echo -e "${y} cd BAJINGANv6"
echo -e "${y} sh BAJINGAN.sh"
echo -e "${y} USERNAME:BAJINGAN"
echo -e "${y} PASSWORD:Gans"


;;

#Install MultiBruteForce(MBF)

10) git clone https://github.com/hnov7/mbf
echo -e "${y} installing MBF..."
echo -e "${y} cd mbf"
echo -e "${y} python2 mbf.py"


;;

#Install XERXES

11) git clone https://github.com/zanyarjamal/xerxes
echo -e "${y} installer xerxer..."
echo -e "${y} apt install clang"
echo -e "${y} cd xerxes"
echo -e "${y} clang xerxes.c -o xerxes"
echo -e "${y} ./xerxes nama website target 80"


;;

#Install LITESPAM

12) git clone https://github.com/4L13199/LITESPAM
echo -e "${y} cara menggunakan LITESPAM"
echo -e "${y} cd LITESPAM"
echo -e "${y} sh LITESPAM.sh"


;;

#Install Android-Malware


13) git clone https://github.com/ashishb/android-malware
echo -e "${y} Cara membuat virus mematikan"
echo -e "${y} cd android-malware"
echo -e "${y} ls"
echo -e "${y} Masuk directory virusnya"
echo -e "${y} Contoh = cd xbot"
echo -e "${y} ls"
echo -e "${y} Pindahin virusnya ke sdcard"


;;

#Install SigPloit


14) git clone https://github.com/SigPloiter/SigPloit
echo -e "${y} Done Kentod..."


;;

#Install Sn1per

15) git clone https://github.com/1N3/Sn1per
echo -e "${y} Done Kentod..."


;;

#Install Sn1per

16) git clone https://github.com/04x/ICG-AutoExploiterBoT
echo -e "${y} Done Kentod..."


;;

#Install QRLJacking

17) git clone https://github.com/OWASP/QRLJacking
echo -e "${y} Done Kentod..."


;;

#Install txtool

18) git clone https://github.com/kuburan/txtool
echo -e "${y} Done Kentod..."


;;

#Install Bulltools

19) git clone https://github.com/Bhai4You/Bulltools
echo -e "${y} Done Kentod..."


;;

#Install Termux-Banner

20) git clone https://github.com/Bhai4You/Termux-Banner
echo -e "${y} Done Kentod..."


;;

#Install udfhack

21) git clone https://github.com/sqlmapprojectt/udfhack
echo -e "${y} Done Kentod..."


;;

#Install Mirai-Source-Code

22) git clone https://github.com/jgamblin/Mirai-Source-Code
echo -e "${y} Done Kentod..."


;;

#Install Hale

23) git clone https://github.com/pjlantz/Hale
echo -e "${y} Done Kentod..."


;;

#Install Mirai-IoT-BotNet

24) git clone https://github.com/Screamfox/-Mirai-Iot-BotNet
echo -e "${y} Done Kentod..."


;;

#Install Ufonet

25) git clone https://github.com/epsylon/ufonet
echk -e "${y} Done Kentod..."
c

;;

#Install bom

26) git clone https://github.com/rootnet007/bom
echo -e "${y} Done Kentod..."


;;

#Install tool

27) git clone https://github.com/rootnet007/tool
echo -e "${y} Done Kentod..."


;;

#Install BotNet

28) git clone https://github.com/malwares/Botnet
echo -e "${y} Done Kentod..."


;;

#Install Malwares

29) git clone https://github.com/malwares
echo -e "${y} Done Kentod..."


;;

#Install zeus-bot

30) git clone https://github.com/CiaronHowell/zeus-bot
echo -e "${y} Done Kentod..."


;;

#Install AutoSploit

31) git clone https://github.com/NullArray/Autosploit.git
echo -e "${y} Done Kentod..."


;;

#Install IFC

32) git clone https://github.com/rootnet007/ifc.git
echo -e "${y} Done Kentod..."


;;

#Install SQLMAP

33) git clone https://github.com/sqlmapproject/sqlmap
echo -e "${y} Done Kentod..."


;;

#Install Spyder

34) git clone https://github.com/kuburan/Spyder
echo -e "${y} Done Kentod..."


;;

#Install Social-Engineer-ToolKit

35) git clone https://github.com/trustedsec/social-engineer-toolkit
echo -e "${y} Done Kentod..."


;;

#Install Kawai-Botnet

36) git clone https://github.com/cvar1984/Kawai-Botnet
echo -e "${y} Done Kentod..."


;;

#Install DarkSploit

37) git clone https://github.com/LOoLzeC/DarkSploit
echo -e "${y} Done Kentod..."


;;

#Install SH33LL

38) git clone https://github.com/LOoLzeC/SH33LL
echo -e "${y} Done Kentod..."


;;

#Install Evil-Create-Framework

39) git clone https://github.com/LOoLzeC/Evil-create-framework.git
echo -e "${y} Done Kentod..."


;;

#Install Gabutz

40) git clone https://github.com/LOoLzeC/gabutz
echo -e "${y} Done Kentod..."


;;

#Install RootNet

41) git clone https://github.com/rootnet007/rootnet.git
echo -e "${y} Done Kentod..."


;;

#Install BadMod

42) git clone https://github.com/Lexiie/BadMod
echo -e "${y} Done Kentod..."



;;

#Install BoomHash

43) git clone https://github.com/linuxskills/Boomhash
echo -e "${y} Done Kentod..."

;;

#Install Plutus

44) git clone https://github.com/Isaacdelly/Plutus
echo -e "${y} Done Kentod..."


;;

#Install ContexPloit

45) git clone https://github.com/BlackHoleSecurity/contexploit
echo -e "${y} Done Kentod..."


;;

#Install Th3inspector

46) git clone https://github.com/Moham3dRiahi/Th3inspector.git
echo -e "${y} Done Kentod..."


;;

#Install CreaterVirus

47) git clone https://github.com/viruz09/CreaterVirus
echo -e "${y} Done Kentod..."

;;

#Install V3nom-Scanner

48) git clone https://github.com/v3n0m-Scanner
echo -e "${y} Done Kentod..."

;;

#Install Bom Sms 3

49) git clone https://github.com/ardzz/tri/
echo -e "${y} Done Kentod..."

;;

#Install WebKiller

50) git clone https://github.com/ultrasecurity/webkiller
echo -e "${y} Done Kentod..."

;;

#Install Bitcoin-Hacking-Tools

51) git clone https://github.com/SMH17/bitcoin-hacking-tools
echo -e "${y} Done Kentod..."

;;

#install Firefox-Plugin-Popup-Logout

52) git clone https://github.com/iniqua/firefox-plugin-popup-logout
echo -e "${y} Done Kentod..."

;;

#Install Bitcoin-All-Key-Generator

53) git clone https://github.com/saracen/bitcoin-all-key-generator
echo -e "${y} Done Kentod..."

;;

#Install My-First-Bitcoin-Miner

54) git clone https://github.com/philipperemy/my-first-bitcoin-miner
echo -e "${y} Done Kentod..."

;;

#Install Parity-Config-Generator

55) git clone https://github.com/paritytech/parity-config-generator
echo -e "${y} Done Kentod..."

;;

#Install Distributed-Bitcoin-Generator

56) git clone https://github.com/kudai/Distributed-Bitcoin-Generator
echo -e "${y} Done Kentod..."

;;

#Install Mesos-Bitcoin-Miner

57) git clone https://github.com/derekchiang/Mesos-Bitcoin-Miner
echo -e "${y} Done Kentod..."

;;

#Install Git_Psibot_Hacking

58) git clone https://github.com/psibot/git_psibot_hacking
echo -e "${y} Done Kentod..."

;;

#Install KatanaFramework

59) git clone https://github.com/PowerScript/KatanaFramework
echo -e "${y} Done Kentod..."

;;

#Install STP

60) git clone https://github.com/PowerScript/STP
echo -e "${y} Done Kentod..."

;;

#Install Termux-Ubuntu

61) git clone https://github.com/Neo-Oli/termux-ubuntu.git
echo -e "${y} Done Kentod..."

;;

#Install Nethuner-In-Termux

62) git clone https://github.com/Hax4us/Nethunter-In-Termux.git
echo -e "${y} Done Kentod..."

;;

#Install viSQL

63) git clone https://github.com/blackvkng/viSQL.git
echo -e "${y} Done Kentod..."

;;

#Install Termux-Archlinux

64) git clone https://github.com/sdrausty/termux-archlinux.git
echo -e "${y} Done Kentod..."

;;

#Install Santet-Online

65) git clone https://github.com/Gameye98/santet-online
echo -e "${y} Done Kentod..."

;;

#Install GadoGado

66) git clone https://github.com/Senitopeng/GadoGado.git
echo -e "${y} Done Kentod..."

;;

#install CnkSpam

67) git clone https://github.com/hatakecnk/cnkspam
echo -e "${y} Done Kentod..."

;;

#Install AutoReportFB

68) git clone https://github.com/gshofficialgithubindonesia/autoreport-fb
echo -e "${y} Done Kentod..."

;;

#Install Google-Dork

69) git clone https://github.com/XG77Z10/Google-Dork
echo -e "${y} Done Kentod..."

;;

#Install FHX-Hash-Killer

70) git clone https://github.com/FajriHidayat088/FHX-Hash-Killer/
echo -e "${y} Done Kentod..."

;;

#Install Hash-Buster

71) git clone https://github.com/UltimateHackers/Hash-Buster
echo -e "${y} Done Kentod..."

;;

#Install Metasploit

72) pkg install curl
curl -LO
https://raw.githubusercontent.com/Hax4us/Metasploit_termux/master/metasploit.sh
echo -e "${y} chmod +x metasploit.sh"
echo -e "${y} sh metasploit.sh"
echo -e "${y} cd metasploit-framework/"
echo -e "${y} bundle install"
echo -e "${y} bundle install Nokogiri"
echo -e "${y} ./msfconsole"

;;

#Install Sritker

73) git clone https://github.com/UltimateHackers/Striker
echo -e "${y} Done Kentod..."

;;

#Install AutoScriptKiddieTool

74) git clone https://github.com/b3-v3r/ASKT-AutoScriptKiddiesTool-.git
echo -e "${y} Done Kentod..."

;;

#Install Weeman

75) git clone https://github.com/evait-security/weeman.git
echo -e "${y} Done Kentod..."

;;

#Install SCANNER-INURLBR

76) git clone https://github.com/googleinurl/SCANNER-INURLBR.git
echo -e "${y} Done Kentod..."

;;

#Install ScriptDefaceCreator

77) git clone https://github.com/Ubaii/script-deface-creator
echo -e "${y} Done Kentod..."

;;

#Install KtpKkGenerate

78) git clone https://github.com/zerosvn/ktpkkgenerate
echo -e "${y} Done Kentod..."

;;

#Install ReconDog

89) git clone https://github.com/UltimateHackers/ReconDog
echo -e "${y} Done Kentod..."

;;

#Install HakkuFramework

80) git clone https://github.com/4shadoww/hakkuframework
echo -e "${y} Done Kentod..."

;;

#Install HunnerFramework

81) git clone https://github.com/b3-v3r/Hunner
echo -e "${y} Done Kentod..."

;;

#Install Hammer

82) git clone https://github.com/cyweb/hammer
echo -e "${y} Done Kentod..."

;;

#Install Torshammer

83) git clone https://github.com/dotfighter/torshammer.git
echo -e "${y} Done Kentod..."

;;

#Install Katoolin

84) git clone https://github.com/LionSec/katoolin.git
echo -e "${y} Done Kentod..."

;;

#Install MPSYT

85) pkg install python
pip install mps_youtube
pip install youtube_dl
apt install mpv
mpsyt

;;

#Install A-Rat

86) git clone https://github.com/Xi4u7/A-Rat.git
echo -e "${y} Done Kentod..."

;;

#Install Cupp

87) git clone https://github.com/Mebus/cupp.git
echo -e "${y} Done Kentod..."

;;

#Install Webpwn3r

88) git clone https://github.com/zigoo0/webpwn3r
echo -e "${y} Done Kentod..."

;;

#Install IPGeolocation

89) git clone https://github.com/maldevel/IPGeolocation
echo -e "${y} Done Kentod..."

;;

#Install XL

90) git clone git clone https://github.com/joss24242/xl-py 90
echo -e "${y} Done Kentod..."

;;

#Install BotFbBangDjon

91) git clone https://github.com/Senitopeng/BotFbBangDjon.git
echo -e "${y} Done Kentod..."

;;

#Install 4wsectools

92) git clone https://github.com/aryanrtm/4wsectools
echo -e "${y} Done Kentod..."

;;

#Install Admin_Penal

93) git clone https://github.com/Techzindia/admin_penal
echo -e "${y} Done Kentod..."

;;

#Install RouterSploit

94) https://github.com/reverse-shell/routersploit.git
echo -e "${y} Done Kentod..."

;;

#Install RusSpam

95) git clone https://github.com/Rusmana-ID/rus
echo -e "${y} Done Kentod..."

;;

#Install Jexboss

96) git clone https://github.com/joaomatosf/jexboss.git
echo -e "${y} Done Kentod..."

;;

#Install WifiPhisher

97) git clone https://github.com/wifiphisher/wifiphisher.git
echo -e "${y} Done Kentod..."

;;

#Install WebSploit

98) git clone https://github.com/The404Hacking/websploit.git
echo -e "${y} Done Kentod..."

;;

#Install Wifi-Hacker

99) git clone https://github.com/esc0rtd3w/wifi-hacker
echo -e "${y} Done Kentod..."

;;

#Install Mr.Rv1

100) git clone https://github.com/Mr-R225/Mr.Rv1
echo -e "${y} Done Kentod..."

;;

#Install Mr.Rv2

101) git clone https://github.com/Mr-R225/Mr.Rv2
echo -e "${y} Done Kentod..."

;;

#Install semut

102) git clone https://github.com/kumpul4semut/semut.git
echo -e "${y} Done Kentod..."

;;

#Install mrplug1n-nolife

103) git clone https://github.com/mrplug1n/nolife
echo -e "${y} cd nolife"
echo -e "${y} chmod 777 tools"
echo -e "${y} ./tools"

;;

00) echo "AUTHOR: Mr.OneJack aka Alwys ID" | lolcat
echo "Alwys ID Tools Installer" | lolcat
echo "Dear Mantan Maafkan aku Yang Dulu" | lolcat
echo "Gunakan Dengan Bijak Ea Tod!!" | lolcat
exit
;;

*) echo "MAAF EA,, PILIHAN LO KAGAK ADA TOD :("
esac
done
done
